### ISSUE TITLE
binary_mask question

### ISSUE THREAD

**Issue by sigma098123** [Yang-Bob/PMMs#10]
Hi Bob
I integrated the binary maps in accordance with the requirements of the comments, then canceled all the comments related to the binary maps, commented the relevant codes, and wanted to try the effects of the binary map, but I got an error. Excuse me, The comment is cancelled, do other operations need to be performed?

Sorry my English is not very well, My idea is that I used the code related to the binary maps to run the entire experiment, but the code reported an error. Can I use all the codes related to the binary maps to successfully run the code?

**Comment by Yang-Bob** [comment]
Hi, I get it.

The binary map is not necessary for our code which can be delet. It is just a mask reading method using binary mask instead of the original mask convert to binary. The performances are the same with it or using current mask reader. For the simplicity of the code, I do not push the binary map to the github. Your error may be the data or data direction does not exit.
In order to not mislead users, I will delet relevant code.
If you still want to use it, you can download the dinary map from [https://github.com/icoz69/CaNet/blob/master/Binary_map_aug.zip](https://github.com/icoz69/CaNet/blob/master/Binary_map_aug.zip).

**Comment by sigma098123** [comment]
Thanks for your reply, I found the link to the paper from your github before, so I have downloaded the corresponding binary maps data and changed the path. My main problem is that the reading of the binary map is annotated in your code , I canceled the comment and annotated the original reading method. I want to read the binary map in this way, but the code is reported wrong. I want to know about it. I want to know, after downloading his data set, whether to read the pictures in the format of the downloaded 20 folders, or to integrate the pictures into a folder to read the pictures, or you can’t only use the code to read binary maps. I just want to figure out where the problem is.


This is my fault
Traceback (most recent call last):
  File "/media/sigma/Files/sigmacode/PMMs/train.py", line 123, in <module>
    train(args)
  File "/media/sigma/Files/sigmacode/PMMs/train.py", line 64, in train
    train_loader = data_loader(args)
  File "/media/sigma/Files/sigmacode/PMMs/data/LoadDataSeg.py", line 30, in data_loader
    img_train = voc_train(args, transform=tsfm_train)
  File "/media/sigma/Files/sigmacode/PMMs/data/voc_train.py", line 38, in __init__
    self.list_splite = self.get_total_list()
  File "/media/sigma/Files/sigmacode/PMMs/data/voc_train.py", line 73, in get_total_list
    new_exist_class_list = self.filte_multi_class(new_exist_class_list)
  File "/media/sigma/Files/sigmacode/PMMs/data/voc_train.py", line 83, in filte_multi_class
    labels = np.unique(mask[:,:,0])
TypeError: 'NoneType' object is not subscriptable

**Comment by Yang-Bob** [comment]
Your error `'NoneType' object is not subscriptable` may be that the `mask` is not existed. More specifically, this error is that the data is empty mainly caused by read error. I think you could check the data directory to find whether the data is loaded correctly, (e.g. printing the mask path etc.).
