### ISSUE TITLE
Model selection

### ISSUE THREAD

**Issue by mboudiaf** [Yang-Bob/PMMs#11]
Hi,
Thank you for your great work and for releasing the code. I am currently trying to train my own models from scratch, but I can't see from the code how the "best" model is selected during training, as they are all just saved as step_x.pth.tar, hence my question : based on which criterion did you select the "best" model for inference.
Thank you in advance :)

Malik

**Comment by Yang-Bob** [comment]
Hi,

Thank you for your attention to our work. 
After training the network, you can use `python test_all_frame.py` to test your own models. In this code, all of the models saved in training stage are tested. Since the four split is independent cross validation, the best model in each split is the highest performance one. After the code finnished, you will get which of the model in each spit is the best.
I hope it will help you!

Bob

**Comment by mboudiaf** [comment]
Hi,

Yes, it helps me. Thank you for your answer :)

Malik
